# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: MyWindowsAgentPool  # Your self-hosted agent pool

steps:
# 1️⃣ Install Node.js 18
- task: NodeTool@0
  inputs:
    versionSpec: '18.x'
  displayName: 'Install Node.js 18'

# 2️⃣ Clean install and build (single step)
- script: |
    echo "Removing old node_modules and lockfile..."
    rm -rf node_modules
    rm -f package-lock.json
    echo "Installing dependencies..."
    npm install
    echo "Building project..."
    npm run build
  displayName: 'Clean install and build'
  env:
    NODE_ENV: development  # Or production if you are sure devDependencies are not needed

# 3️⃣ Optional: Run tests
- script: |
    npm test
  displayName: 'Run tests'